# Rubocop plugins to include.
require: "rubocop-rspec"

# Alignment of hash rockets, keys are right aligned.
Style/AlignHash:
  EnforcedHashRocketStyle: "separator"

# Use double quotes in string literals.
StringLiterals:
  EnforcedStyle: "double_quotes"
StringLiteralsInInterpolation:
  EnforcedStyle: "double_quotes"

# Don't consider comments when counting method length.
Metrics/MethodLength:
  CountComments: false

# Single line method definitions don't need an empty line between them.
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Use slashes on single-line regexes, and %r on multi-line regexes.
Style/RegexpLiteral:
  EnforcedStyle: mixed

# Allow unicode symbols in comments.
AsciiComments:
  Enabled: false
