source "https://rubygems.org"

# For faster file watcher updates on Windows.
gem "wdm", "~> 0.1", platforms: [:mswin, :mingw]

# Windows does not come with time zone data.
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]

# Middleman gems.
gem "middleman", "~> 4.2"
